# ####################################################################

#  Created by Genus(TM) Synthesis Solution 21.14-s082_1 on Tue Jul 21 11:43:22 IST 2026

# ####################################################################

set sdc_version 2.0

set_units -capacitance 1000fF
set_units -time 1000ps

# Set the current design
current_design mesh_4x4_top

create_clock -name "clk" -period 20.0 -waveform {0.0 10.0} [get_ports clk]
set_clock_transition 0.2 [get_clocks clk]
set_load -pin_load 0.05 [get_ports {pe_in_ready[15]}]
set_load -pin_load 0.05 [get_ports {pe_in_ready[14]}]
set_load -pin_load 0.05 [get_ports {pe_in_ready[13]}]
set_load -pin_load 0.05 [get_ports {pe_in_ready[12]}]
set_load -pin_load 0.05 [get_ports {pe_in_ready[11]}]
set_load -pin_load 0.05 [get_ports {pe_in_ready[10]}]
set_load -pin_load 0.05 [get_ports {pe_in_ready[9]}]
set_load -pin_load 0.05 [get_ports {pe_in_ready[8]}]
set_load -pin_load 0.05 [get_ports {pe_in_ready[7]}]
set_load -pin_load 0.05 [get_ports {pe_in_ready[6]}]
set_load -pin_load 0.05 [get_ports {pe_in_ready[5]}]
set_load -pin_load 0.05 [get_ports {pe_in_ready[4]}]
set_load -pin_load 0.05 [get_ports {pe_in_ready[3]}]
set_load -pin_load 0.05 [get_ports {pe_in_ready[2]}]
set_load -pin_load 0.05 [get_ports {pe_in_ready[1]}]
set_load -pin_load 0.05 [get_ports {pe_in_ready[0]}]
set_load -pin_load 0.05 [get_ports {pe_out_valid[15]}]
set_load -pin_load 0.05 [get_ports {pe_out_valid[14]}]
set_load -pin_load 0.05 [get_ports {pe_out_valid[13]}]
set_load -pin_load 0.05 [get_ports {pe_out_valid[12]}]
set_load -pin_load 0.05 [get_ports {pe_out_valid[11]}]
set_load -pin_load 0.05 [get_ports {pe_out_valid[10]}]
set_load -pin_load 0.05 [get_ports {pe_out_valid[9]}]
set_load -pin_load 0.05 [get_ports {pe_out_valid[8]}]
set_load -pin_load 0.05 [get_ports {pe_out_valid[7]}]
set_load -pin_load 0.05 [get_ports {pe_out_valid[6]}]
set_load -pin_load 0.05 [get_ports {pe_out_valid[5]}]
set_load -pin_load 0.05 [get_ports {pe_out_valid[4]}]
set_load -pin_load 0.05 [get_ports {pe_out_valid[3]}]
set_load -pin_load 0.05 [get_ports {pe_out_valid[2]}]
set_load -pin_load 0.05 [get_ports {pe_out_valid[1]}]
set_load -pin_load 0.05 [get_ports {pe_out_valid[0]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[191]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[190]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[189]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[188]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[187]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[186]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[185]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[184]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[183]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[182]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[181]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[180]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[179]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[178]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[177]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[176]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[175]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[174]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[173]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[172]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[171]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[170]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[169]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[168]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[167]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[166]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[165]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[164]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[163]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[162]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[161]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[160]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[159]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[158]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[157]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[156]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[155]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[154]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[153]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[152]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[151]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[150]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[149]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[148]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[147]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[146]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[145]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[144]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[143]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[142]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[141]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[140]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[139]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[138]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[137]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[136]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[135]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[134]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[133]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[132]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[131]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[130]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[129]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[128]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[127]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[126]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[125]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[124]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[123]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[122]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[121]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[120]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[119]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[118]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[117]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[116]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[115]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[114]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[113]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[112]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[111]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[110]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[109]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[108]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[107]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[106]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[105]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[104]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[103]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[102]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[101]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[100]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[99]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[98]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[97]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[96]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[95]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[94]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[93]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[92]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[91]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[90]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[89]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[88]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[87]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[86]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[85]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[84]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[83]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[82]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[81]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[80]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[79]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[78]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[77]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[76]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[75]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[74]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[73]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[72]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[71]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[70]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[69]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[68]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[67]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[66]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[65]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[64]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[63]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[62]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[61]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[60]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[59]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[58]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[57]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[56]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[55]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[54]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[53]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[52]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[51]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[50]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[49]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[48]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[47]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[46]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[45]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[44]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[43]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[42]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[41]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[40]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[39]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[38]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[37]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[36]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[35]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[34]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[33]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[32]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[31]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[30]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[29]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[28]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[27]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[26]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[25]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[24]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[23]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[22]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[21]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[20]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[19]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[18]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[17]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[16]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[15]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[14]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[13]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[12]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[11]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[10]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[9]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[8]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[7]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[6]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[5]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[4]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[3]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[2]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[1]}]
set_load -pin_load 0.05 [get_ports {pe_out_data[0]}]
set_false_path -from [get_ports rst_n]
set_clock_gating_check -setup 0.0 
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_valid[15]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_valid[14]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_valid[13]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_valid[12]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_valid[11]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_valid[10]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_valid[9]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_valid[8]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_valid[7]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_valid[6]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_valid[5]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_valid[4]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_valid[3]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_valid[2]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_valid[1]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_valid[0]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[191]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[190]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[189]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[188]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[187]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[186]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[185]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[184]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[183]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[182]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[181]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[180]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[179]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[178]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[177]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[176]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[175]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[174]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[173]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[172]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[171]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[170]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[169]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[168]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[167]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[166]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[165]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[164]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[163]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[162]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[161]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[160]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[159]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[158]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[157]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[156]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[155]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[154]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[153]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[152]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[151]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[150]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[149]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[148]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[147]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[146]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[145]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[144]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[143]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[142]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[141]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[140]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[139]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[138]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[137]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[136]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[135]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[134]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[133]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[132]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[131]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[130]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[129]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[128]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[127]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[126]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[125]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[124]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[123]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[122]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[121]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[120]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[119]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[118]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[117]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[116]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[115]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[114]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[113]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[112]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[111]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[110]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[109]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[108]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[107]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[106]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[105]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[104]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[103]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[102]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[101]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[100]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[99]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[98]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[97]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[96]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[95]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[94]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[93]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[92]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[91]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[90]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[89]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[88]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[87]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[86]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[85]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[84]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[83]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[82]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[81]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[80]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[79]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[78]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[77]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[76]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[75]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[74]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[73]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[72]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[71]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[70]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[69]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[68]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[67]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[66]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[65]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[64]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[63]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[62]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[61]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[60]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[59]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[58]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[57]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[56]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[55]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[54]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[53]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[52]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[51]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[50]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[49]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[48]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[47]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[46]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[45]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[44]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[43]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[42]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[41]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[40]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[39]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[38]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[37]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[36]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[35]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[34]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[33]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[32]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[31]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[30]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[29]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[28]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[27]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[26]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[25]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[24]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[23]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[22]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[21]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[20]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[19]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[18]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[17]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[16]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[15]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[14]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[13]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[12]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[11]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[10]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[9]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[8]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[7]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[6]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[5]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[4]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[3]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[2]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[1]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_data[0]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_ready[15]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_ready[14]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_ready[13]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_ready[12]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_ready[11]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_ready[10]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_ready[9]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_ready[8]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_ready[7]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_ready[6]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_ready[5]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_ready[4]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_ready[3]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_ready[2]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_ready[1]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_ready[0]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports rst_n]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_ready[15]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_ready[14]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_ready[13]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_ready[12]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_ready[11]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_ready[10]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_ready[9]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_ready[8]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_ready[7]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_ready[6]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_ready[5]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_ready[4]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_ready[3]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_ready[2]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_ready[1]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_in_ready[0]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_valid[15]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_valid[14]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_valid[13]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_valid[12]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_valid[11]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_valid[10]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_valid[9]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_valid[8]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_valid[7]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_valid[6]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_valid[5]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_valid[4]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_valid[3]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_valid[2]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_valid[1]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_valid[0]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[191]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[190]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[189]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[188]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[187]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[186]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[185]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[184]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[183]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[182]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[181]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[180]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[179]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[178]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[177]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[176]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[175]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[174]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[173]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[172]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[171]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[170]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[169]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[168]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[167]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[166]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[165]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[164]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[163]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[162]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[161]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[160]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[159]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[158]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[157]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[156]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[155]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[154]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[153]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[152]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[151]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[150]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[149]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[148]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[147]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[146]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[145]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[144]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[143]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[142]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[141]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[140]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[139]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[138]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[137]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[136]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[135]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[134]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[133]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[132]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[131]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[130]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[129]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[128]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[127]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[126]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[125]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[124]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[123]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[122]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[121]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[120]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[119]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[118]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[117]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[116]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[115]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[114]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[113]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[112]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[111]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[110]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[109]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[108]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[107]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[106]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[105]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[104]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[103]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[102]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[101]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[100]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[99]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[98]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[97]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[96]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[95]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[94]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[93]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[92]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[91]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[90]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[89]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[88]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[87]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[86]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[85]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[84]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[83]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[82]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[81]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[80]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[79]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[78]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[77]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[76]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[75]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[74]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[73]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[72]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[71]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[70]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[69]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[68]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[67]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[66]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[65]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[64]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[63]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[62]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[61]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[60]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[59]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[58]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[57]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[56]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[55]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[54]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[53]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[52]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[51]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[50]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[49]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[48]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[47]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[46]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[45]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[44]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[43]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[42]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[41]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[40]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[39]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[38]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[37]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[36]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[35]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[34]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[33]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[32]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[31]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[30]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[29]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[28]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[27]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[26]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[25]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[24]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[23]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[22]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[21]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[20]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[19]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[18]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[17]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[16]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[15]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[14]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[13]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[12]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[11]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[10]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[9]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[8]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[7]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[6]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[5]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[4]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[3]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[2]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[1]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {pe_out_data[0]}]
set_wire_load_mode "enclosed"
set_dont_use true [get_lib_cells tsl18fs120_scl_ss/slbhb2]
set_dont_use true [get_lib_cells tsl18fs120_scl_ss/slbhb1]
set_dont_use true [get_lib_cells tsl18fs120_scl_ss/slbhb4]
set_clock_uncertainty -setup 0.5 [get_clocks clk]
set_clock_uncertainty -hold 0.5 [get_clocks clk]
